#!/bin/python

import heapq
import numpy as np
import sys

INF = 9999

dpath = sys.argv[ 1 ]

lines = []
with open( dpath ) as f:
  for l in f:
    l = l.strip()
    lines.append( l.strip() )

W = len( lines[ 0 ])
H = len( lines )
M = np.zeros(( H, W ), np.int8 )
Sr, Sc, Er, Ec = 0, 0, 0, 0
orda = ord( 'a' )
act = 0
for r, line in enumerate( lines ):
  for c, ch in enumerate( lines[ r ]):
    if ch == 'a' or ch == 'S':
      act += 1
    if ch == 'S':
      Sr, Sc, h = r, c, 0
      act += 1
    elif ch == 'E':
      Er, Ec, h = r, c, 25
    else:
      h = ord( ch ) - orda
    M[ r ][ c ] = h

class Node:
  def __init__( self, r, c, h ):
    self.r, self.c, self.h, self.s = r, c, h, INF
  def __eq__( self   ,  other ):
    return    self.s == other.s
  def __ne__( self   ,  other ):
    return    self.s != other.s
  def __gt__( self   ,  other ):
    return    self.s >  other.s
  def __lt__( self   ,  other ):
    return    self.s <  other.s
  def __ge__( self   ,  other ):
    return    self.s >= other.s
  def __le__( self   ,  other ):
    return    self.s <= other.s
  def __repr__( self ):
    return '[{},{},{}] {}'.format( self.r, self.c, self.h, self.s )

noderc = []
nodelist = []
for r in range( H ):
  nodec = []
  noderc.append( nodec )
  for c in range( W ):
    n = Node( r, c, M[ r, c ])
    if r == Sr and c == Sc: n.s = 0
    nodelist.append( n )
    nodec.append( n )

nodes = [ n for n in nodelist ]
heapq.heapify( nodes )
while nodes:

  n = heapq.heappop( nodes )
  r, c = n.r, n.c
  s = n.s + 1
  h = n.h + 1 # M[ r ][ c ] + 1 # height of neighbour we can reach
  nsew = [            # coords of neighbours
    ( r - 1, c )
  , ( r + 1, c )
  , ( r, c + 1 )
  , ( r, c - 1 )
  ]
  mod = False
  for y, x in nsew:
    if y < 0 or y == H or x < 0 or x == W: continue
    _n = noderc[ y ][ x ]
    if _n.h <= h and s < _n.s:
      _n.s = s
      mod = True
  if mod: nodes.sort()

print( 'part1', noderc[ Er ][ Ec ].s )

nodes = []
for node in nodelist:
  node.s = 0 if node.r == Er and node.c == Ec else INF
  nodes.append( node )
heapq.heapify( nodes )
smin = INF
while nodes:

  n = heapq.heappop( nodes )
  r, c = n.r, n.c
  s = n.s + 1
  h = M[ r ][ c ] - 1 # height of neighbour we can reach
  nsew = [            # coords of neighbours
    ( r - 1, c )
  , ( r + 1, c )
  , ( r, c + 1 )
  , ( r, c - 1 )
  ]
  mod = False
  for y, x in nsew:
    if y < 0 or y == H or x < 0 or x == W: continue
    _n = noderc[ y ][ x ]
    if _n.h >= h and s < _n.s:
      _n.s = s
      if _n.h == 0 and s < smin: smin = s
      mod = True
  if mod: nodes.sort()

print( 'part2', smin )

