#!/bin/python

src = 'd0'
#rc = 'd1'
src = 'dat'

m = []
with open( src ) as f:
    for l in f:
        m.append( l.strip() )
 
w = len( m[ 0 ])
h = len( m )
l = [ '.' for c in range( w )]
n = [ l[:] for r in range( h )]
 
t1, _w, _h = 0, w - 3, h - 3
for r in range( h ):
    for c in range( w ):
        if m[r][c] != 'X': continue
        if r > 2:
            if c > 2 and m[r-1][c-1] == 'M' and m[r-2][c-2] == 'A' and m[r-3][c-3] == 'S':
                t1 += 1
                n[r][c], n[r-1][c-1], n[r-2][c-2], n[r-3][c-3] = 'X', 'M', 'A', 'S'
            if c < _w and m[r-1][c+1] == 'M' and m[r-2][c+2] == 'A' and m[r-3][c+3] == 'S':
                t1 += 1
                n[r][c], n[r-1][c+1], n[r-2][c+2], n[r-3][c+3] = 'X', 'M', 'A', 'S'
            if m[r-1][c] == 'M' and m[r-2][c] == 'A' and m[r-3][c] == 'S':
                t1 += 1
                n[r][c], n[r-1][c], n[r-2][c], n[r-3][c] = 'X', 'M', 'A', 'S'
        if r < _h:
            if c > 2 and m[r+1][c-1] == 'M' and m[r+2][c-2] == 'A' and m[r+3][c-3] == 'S':
                t1 += 1
                n[r][c], n[r+1][c-1], n[r+2][c-2], n[r+3][c-3] = 'X', 'M', 'A', 'S'
            if c < _w and m[r+1][c+1] == 'M' and m[r+2][c+2] == 'A' and m[r+3][c+3] == 'S':
                t1 += 1
                n[r][c], n[r+1][c+1], n[r+2][c+2], n[r+3][c+3] = 'X', 'M', 'A', 'S'
            if m[r+1][c] == 'M' and m[r+2][c] == 'A' and m[r+3][c] == 'S':
                t1 += 1
                n[r][c], n[r+1][c], n[r+2][c], n[r+3][c] = 'X', 'M', 'A', 'S'
        if c > 2 and m[r][c-1] == 'M' and m[r][c-2] == 'A' and m[r][c-3] == 'S':
            t1 += 1
            n[r][c], n[r][c-1], n[r][c-2], n[r][c-3] = 'X', 'M', 'A', 'S'
        if c < _w and m[r][c+1] == 'M' and m[r][c+2] == 'A' and m[r][c+3] == 'S':
            t1 += 1
            n[r][c], n[r][c+1], n[r][c+2], n[r][c+3] = 'X', 'M', 'A', 'S'
#or l in n: print( ''.join( l ))
print( 'part1', t1 ) # 2576 too high
 
t2 = 0
for r in range( 1, h-1 ):
    for c in range( 1, w-1 ):
        if m[r][c] != 'A': continue
        if m[r-1][c-1] == m[r-1][c+1] == 'M' and m[r+1][c-1] == m[r+1][c+1] == 'S' \
        or m[r-1][c-1] == m[r-1][c+1] == 'S' and m[r+1][c-1] == m[r+1][c+1] == 'M' \
        or m[r-1][c-1] == m[r+1][c-1] == 'M' and m[r-1][c+1] == m[r+1][c+1] == 'S' \
        or m[r-1][c-1] == m[r+1][c-1] == 'S' and m[r-1][c+1] == m[r+1][c+1] == 'M' :
            t2 += 1
print( 'part2', t2 )
