#!/bin/python

n0 = None
n1 = None
n2 = None
s0 = None
incs = 0
with open( 'dat' ) as f:
  for l in f:
     n3 = int( l.strip() )
     s1 = n0 + n1 + n2 + n3
     if s0 is not None and s1 > s0:
       incs += 1
     s0, n0, n1, n2 = s1, n1, n2, n3

print( incs )

