#!/bin/python

n0 = None
n1 = None
s0 = None
s1 = None
incs = 0
with open( 'dat' ) as f:
  for l in f:
     n2 = int( l.strip() )
     if n0 is not None:
       s1 = n0 + n1 + n2
       if s0 is not None and s1 > s0:
         incs += 1
     s0, n0, n1 = s1, n1, n2

print( incs )

