#!/bin/python3

src = 'd0'
src = 'dat'

with open( src ) as f:
  seqs = [ l.strip().split() for l in f.readlines() ]
  seqs = [[ int( s ) for s in seq ] for seq in seqs ]

t1, t2 = 0, 0
for seq in seqs:
  l = [ x for x in seq ]
  ls = [ l ]
  while any( x for x in l ):
    l = [ l[ i + 1 ] - l[ i ] for i in range( len( l ) - 1 )]
    ls.append( l )
  #rint( 'ls', ls )
  
  l0 = ls[ -1 ]
  x1 = 0
  x2 = 0
  for l in reversed( ls ):
    x1 = l[ -1 ] + x1
    x2 = l[ 0 ] - x2
  t1 += x1
  t2 += x2

print( 'part1', t1 )
print( 'part2', t2 )
 
