#!/bin/python

import sys
path = sys.argv[ 1 ]

with open( path ) as f:
  l = f.read().strip()

c0, c1, c2 = '0', '0', '0'
sc = 0
for i, c in enumerate( l ):
  if c == c2: sc = 1
  else:
    if c != c2: sc = min( 4, sc + 1 )
    if c == c1: sc = 2
    if c == c0: sc = min( sc, 3 )
  #print( i, sc, c0, c1, c2, c )
  if sc == 4:
    break
  c0 = c1
  c1 = c2
  c2 = c
print( 'part1', i + 1 )

c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12 = \
  '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'
sc = 0
for i, c in enumerate( l ):
  if c == c12: sc = 1
  else:
    if c != c12: sc = min( 14, sc + 1 )
    if c == c11: sc = 2
    if c == c10: sc = min( sc,  3 )
    if c == c9 : sc = min( sc,  4 )
    if c == c8 : sc = min( sc,  5 )
    if c == c7 : sc = min( sc,  6 )
    if c == c6 : sc = min( sc,  7 )
    if c == c5 : sc = min( sc,  8 )
    if c == c4 : sc = min( sc,  9 )
    if c == c3 : sc = min( sc, 10 )
    if c == c2 : sc = min( sc, 11 )
    if c == c1 : sc = min( sc, 12 )
    if c == c0 : sc = min( sc, 13 )
  #print( i, sc, c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c, len( set([ c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c ])))
  if sc == 14:
    break
  c0 = c1
  c1 = c2
  c2 = c3
  c3 = c4
  c4 = c5
  c5 = c6
  c6 = c7
  c7 = c8
  c8 = c9
  c9 = c10
  c10 = c11
  c11 = c12
  c12 = c
print( 'part2', i + 1 )

