#!/bin/python

import sys
path = sys.argv[ 1 ]
with open( path ) as f:
  l = f.read()

l = l.strip()
#print( l, len( l ))
c0, c1, c2 = None, None, None
sc = 0
for i, c in enumerate( l ):
  if c == c2:
    sc = 1
  else:
    if c == c1: sc = max( sc, 2 )
    elif c == c0: sc = max( sc, 3 )
    else: sc += 1
  print( sc, i, c0, c1, c2, c )
  #if i > 2 and c0 != c1 and c0 != c2 and c0 != c and c1 != c2 and c1 != c and c2 != c:
  #  n = i + 1
  #  break
  if sc == 4:
    n = i + 1
    break
  c0 = c1
  c1 = c2
  c2 = c
  if sc == 4: sc = 3
print( 'part1', n ) # 223 low

