#!/bin/python

#hist = { 0: 1, 3: 2 }
hist = { 2: 1, 0: 2, 1: 3, 9: 4, 5: 5 }

print( '0001: 0' )
print( '0002: 3' ) 

turn = 6
num = 19
while True:

    if num not in hist:
        new_num = 0

    else:
        new_num = turn - hist[ num ]

    hist[ num ] = turn
    #rint( '{:04}: {}'.format( turn, num ))
    
    #if turn == 2020:
    #    exit( 0 ) # 910 too low

    if turn %    300000 == 0:
        print( turn )
    if turn == 30000000:
        print( 'part2', num )
        exit( 0 )

    turn += 1
    num = new_num
    #input()
