#!/bin/python3

src = 'd0'
#rc = 'dat'

def load():
  m = []
  with open( src ) as f:
    for l in f:
      m.append( list( l.strip() ))
  return m, len( m ), len( m[ 0 ])

def pr_map():
  print()
  for l in lmap:
    print( ''.join( l ))

def nload():
  t = 0
  for i, l in enumerate( lmap ):
    for c in l:
      if c == 'O':
        t += h - i
  return t

lmap, h, w = load()
#rint( 'h', h, 'w', w )

for i0 in range( 1, h ):
  l0 = lmap[ 0 ]
  for i in range( 1, h + 1 - i0 ):
    #print( 'i0', i0, 'i', i )
    l1 = lmap[ i ]
    for j in range( w ):
      #if i == 9:
      #  print( 'i0', i0, 'l0', l0, 'i', i, 'l1', l1, 'j', j, 'l0[j]', l0[j], 'l1[j]', l1[j] ); input()
      if l0[ j ] == '.' and l1[ j ] == 'O':
        l0[ j ] = 'O'
        l1[ j ] = '.'
    l0 = l1
  #pr_map(); input()

print( 't1', nload() )

def north():
  for i0 in range( 1, h ):
    l0 = lmap[ 0 ]
    for i in range( 1, h + 1 - i0 ):
      #print( 'i0', i0, 'i', i )
      l1 = lmap[ i ]
      for j in range( w ):
        #if i == 2:
        #  print( 'i0', i0, 'l0', l0, 'i', i, 'l1', l1, 'j', j, 'l0[j]', l0[j], 'l1[j]', l1[j] ); input()
        if l0[ j ] == '.' and l1[ j ] == 'O':
          l0[ j ] = 'O'
          l1[ j ] = '.'
      l0 = l1
    #pr_map(); input()

def south():
  for i0 in range( h - 2, -1, -1 ):
    l0 = lmap[ h - 1 ]
    for i in range( h - 2, h - 3 - i0, -1 ):
      print( 'i0', i0, 'i', i, 'h-1', h - 1 )
      l1 = lmap[ i ]
      for j in range( w ):
        #if i == 2:
        #  print( 'i0', i0, 'l0', l0, 'i', i, 'l1', l1, 'j', j, 'l0[j]', l0[j], 'l1[j]', l1[j] ); input()
        if l0[ j ] == '.' and l1[ j ] == 'O':
          l0[ j ] = 'O'
          l1[ j ] = '.'
      l0 = l1
      #pr_map(); input()

def west():
  for l in lmap:
    c0 = lmap[ 0 ]
    for c in lmap[ 
lmap, h, w = load()
south()
pr_map()
print( 't2', nload() )

