#!/bin/python

import itertools as it
import numpy as np
import parse
import sys

dpath = sys.argv[ 1 ]

# y = mx * x + y0
class Line:
  def __init__( self, y0, mx ):
    self.y0, self.mx = y0, mx
  def __repr__( self ):
    #eturn 'y = {} * x + {}'.format( self.mx, self.y0 )
    return '{:16} {:16}'.format( self.mx, self.y0 )
lines = []

x0, y0, x1, y1 = 0, 0, 0, 0
walls = []
pc = parse.compile( 'Sensor at x={:d}, y={:d}: closest beacon is at x={:d}, y={:d}\n' )
sensors = []
y0s = []
with open( dpath ) as f:
  for l in f:

    res = pc.parse( l )
    sx, sy, bx, by = res[ 0 ], res[ 1 ], res[ 2 ], res[ 3 ]
    bm = abs( sx - bx ) + abs( sy - by )
    sensors.append(( sx, sy, bx, by, bm ))

    x0 = min( x0, sx - bm )
    x1 = max( x1, sx + bm )
    y0 = min( y0, sy - bm )
    y1 = max( y1, sy + bm )

    # 4 lines bound the sensor, NW, NE, SW, SE
    #
    #          +
    #     NW  / \ NE
    #        /   \
    #       /     \
    #      +       +
    #       \     / 
    #     SW \   / SE
    #         \ / 
    #          +
    #
    # There is only 1 point where the missing beacon can be, therefore
    # it must be where multiple bounding lines from various sensors
    # cross, so compute all the lines and see how many are duplicate
    #
    # where 2 pairs of duplicated lines intersect is the answer

    # NW line: y = mx * x + x0            mx is +1
    # put in y = sy + bm + 1, x = sx
    # sy + bm + 1 = 1 * sx + x0
    # x0 = sy + bm + 1 - sx
    lines.append( Line( sy + bm + 1 - sx, +1 ))
    lines.append( Line( sy + bm + 1 - sx, -1 ))   # mx is -1 for NE line
    y0s.append( sy + bm + 1 - sx )

    # SE line: y = mx * x + x0            mx is +1
    # put in y = sy - bm - 1, x = sx
    # sy - bm - 1 = 1 * sx + x0
    # x0 = sy - bm - 1 - sx
    lines.append( Line( sy - bm - 1 - sx, +1 ))
    lines.append( Line( sy - bm - 1 - sx, -1 ))
    y0s.append( sy - bm - 1 - sx )

print( sorted( y0s ))
exit()
ctlines = {}
for line in lines:
  if line in ctlines:
    ctlines[ line ] = ctlines[ line ] + 1
  else:
    ctlines[ line ] = 1

for line, ct  in ctlines.items():
  print( line, ct )

print( 'x0: {}, x1: {}, y0: {}, y1: {}'.format( x0, x1, y0, y1 ))

for s0, s1 in it.combinations( sensors, 2 ):
  sx0, sy0, bx0, by0, bm0 = s0
  sx1, sy1, bx1, by1, bm1 = s1
  smd = abs( sx0 - sx1 ) + abs( sy0 - sy1 )
  if abs( smd - bm0 - bm1 ) == 2:
    tx = sx0 + ( sx1 - sx0 ) * bm0 // ( bm0 + bm1 + 2 )
    ty = sy0 + ( sy1 - sy0 ) * bm0 // ( bm0 + bm1 + 2 )
    print( s0, s1, tx, ty, tx * 4000000 + ty )
    #print( tx, ty, tx * 4000000 + ty )
  #print( smd, bm0 + bm1, abs( smd - ( bm0 + bm1 )))

exit()

ty = 10 if dpath == 'd0' else 2000000
print( 'ty', ty )
ct = 0
for tx in range( x0, x1 + 1 ):

  for sx, sy, bx, by, bm in sensors:
    tm = abs( tx - sx ) + abs( ty - sy )

    # if this point is within the sensors manhattan distance and not on its beacon
    if tm <= bm and ( tx, ty ) != ( bx, by ):
      ct += 1
      break

print( 'part1', ct ) # 4403085 low

# 13680211232023 high
# 13704503267076 high
