#!/bin/python

t1, t2 = 0, 0
with open( 'dat' ) as f:
  for l in f:
    l = l.strip()
    l0, l1 = l.split( ',' )
    p0, p1 = l0.split( '-' )
    q0, q1 = l1.split( '-' )
    p0, p1, q0, q1 = int( p0 ), int( p1 ), int( q0 ), int( q1 )
    if p0 >= q0 and p1 <= q1:
      t1 += 1
    elif p0 <= q0 and p1 >= q1:
      t1 += 1
    #if max( p0, q0 ) < min( p1, q1 ):
    if p0 <= q1 and p1 >= q0:
      t2 += 1
print( 'part1', t1 )
print( 'part2', t2, '655 low' )

