#!/bin/python

fname = 'da'

mem = {}
with open( fname ) as f:
  for l in f:
    l = l.strip()
    k, _, v = l.split()
    #print( k, v )
    if k == 'mask':
      m0 = int( v.replace( 'X', '0' ), 2 )
      m1 = int( v.replace( 'X', '1' ), 2 )
      #print( 'm0:  {:036b}'.format( m0 ))
      #print( 'm1:  {:036b}'.format( m1 ))
    else:
      addr = int( k[ 4 : -1 ])
      data = int( v )
      #print( '\n{:036b}\n{:036b}\n{:036b}\n{:036b}'.format( data, data | m0, data & m1, ( data | m0 ) & m1 ))
      mem[ addr ] = ( data | m0 ) & m1

tot = sum( v for v in mem.values() )
print( 'part1', tot )

with open( fname ) as f:
  for l in f:
    l = l.strip()
    k, _, v = l.split()
    if k == 'mask':
      mask = v
    else:
      addr = int( k[ 4 : -1 ])
      data = int( v )
      #print( '\n{:036b}\n{:036b}\n{:036b}\n{:036b}'.format( data, data | m0, data & m1, ( data | m0 ) & m1 ))
      mem[ addr ] = ( data | m0 ) & m1
